controller_list:
  - name: fake_end_effector_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_4
  - name: fake_plan_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
initial:  # Define initial robot poses per group
  - group: plan
    pose: initial